language: php
php:
- 5.3
- 5.4
- 5.5
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  #- secure: QTSIA7B1QoCtpYO9C8GnGlNX/wZeIEQgdKKh5KRPG/DsO1UQLWO5Lwd+ELQlQhlA0jTywIhaLmrPgMU9GFY6GtW0T7Z1esqoOnDIRDzLEYe/GVKXroQRrGbuSzznaIN1Qn9JbqS+7S9TAmQK/hh2hBydoW5fztGB2CsD3iObE6w=
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
notifications:
  email:
    recipients:
    - ghost1227@reduxframework.com
    - dovy@reduxframework.com
    on_success: change
    on_failure: always
branches:
  except:
  - gh-pages
  - setup