language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    #- WP_VERSION=3.6.1 WP_MULTISITE=0
    #- WP_VERSION=3.6.1 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit

notifications:
    email:
        recipients:
          - ghost1227@reduxframework.com
          - dovy@reduxframework.com
        on_success: change
        on_failure: always

# wordpress-plugin-tests specific config
# Tells Travis CI not to run unit tests against the setup branch
branches:
    except:
        - gh-pages
        - setup